# Generated by Django 5.0.6 on 2024-08-31 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0003_recipe_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='ACCESS',
        ),
    ]
