# Generated by Django 5.0.6 on 2024-08-31 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0005_rename_registereduser_cookbook_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cookbook',
        ),
    ]
