# Generated by Django 5.0.6 on 2024-09-03 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0008_rename_author_cookbook_cookbookauthor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookbook',
            name='recipe',
        ),
        migrations.CreateModel(
            name='CookbookRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookbook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='FGPH.cookbook')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FGPH.recipe')),
            ],
        ),
    ]
