# Generated by Django 5.0.6 on 2024-09-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0009_remove_cookbook_recipe_cookbookrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
