# Generated by Django 5.0.6 on 2024-09-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0010_recipe_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.JSONField(null=True),
        ),
    ]
