# Generated by Django 5.0.6 on 2024-09-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0011_alter_recipe_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
