# Generated by Django 5.0.6 on 2024-09-06 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0013_image_remove_recipe_image_recipe_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='photo',
            new_name='image',
        ),
    ]
