# Generated by Django 5.0.6 on 2024-09-06 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0015_remove_recipe_image_image_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='FGPH.recipe'),
        ),
    ]
