# Generated by Django 5.0.6 on 2024-09-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0016_alter_image_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
