# Generated by Django 5.0.6 on 2024-09-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0017_alter_image_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
