# Generated by Django 5.0.6 on 2024-09-06 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0018_recipe_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='thumbnail',
        ),
        migrations.CreateModel(
            name='RecipePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FGPH.image')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FGPH.recipe')),
            ],
        ),
    ]
