# Generated by Django 5.0.6 on 2024-09-06 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0019_remove_image_recipe_remove_recipe_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='FGPH.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='RecipePhoto',
        ),
    ]
