# Generated by Django 5.0.6 on 2024-09-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0020_image_recipe_recipe_thumbnail_delete_recipephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/placeholder.png', null=True, upload_to=''),
        ),
    ]
