# Generated by Django 5.0.6 on 2024-09-07 06:51

import FGPH.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0022_alter_recipe_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to=FGPH.models.get_image_filename, verbose_name='Image')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='FGPH.recipe')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
