# Generated by Django 5.0.6 on 2024-09-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0023_images_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
