# Generated by Django 5.0.6 on 2024-09-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0024_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='acronym',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
