# Generated by Django 5.0.6 on 2024-09-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0027_region_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
