# Generated by Django 5.0.6 on 2024-09-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0028_alter_region_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='acronym',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
