# Generated by Django 5.0.6 on 2024-09-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0029_alter_region_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
