# Generated by Django 5.0.6 on 2024-09-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0030_region_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='order',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
