# Generated by Django 5.0.6 on 2024-09-08 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0031_region_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='acronym',
            new_name='alias',
        ),
    ]
