# Generated by Django 5.0.6 on 2024-09-08 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0032_rename_acronym_region_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='number',
        ),
    ]
