# Generated by Django 5.0.6 on 2024-09-08 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0033_remove_region_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='FGPH.region'),
        ),
    ]
