# Generated by Django 5.0.6 on 2024-09-10 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0037_alter_recipe_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
    ]
