# Generated by Django 5.0.6 on 2024-09-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0038_remove_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Authentic', 'Authentic'), ('Signature', 'Signature')], max_length=64, null=True),
        ),
    ]
