# Generated by Django 5.0.6 on 2024-09-10 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0039_recipe_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
