# Generated by Django 5.0.6 on 2024-09-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0044_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Categories'),
        ),
    ]
