# Generated by Django 5.0.6 on 2024-09-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0047_alter_recipe_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(default='placeholder.png', upload_to=''),
        ),
    ]
