# Generated by Django 5.0.6 on 2024-09-10 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0048_alter_recipe_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbookrecipe',
            name='cookbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='FGPH.cookbook'),
        ),
    ]
