# Generated by Django 5.0.6 on 2024-09-10 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0049_alter_cookbookrecipe_cookbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbook',
            name='cookbookAuthor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='FGPH.registereduser'),
        ),
        migrations.AlterField(
            model_name='cookbookrecipe',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FGPH.recipe'),
        ),
        migrations.AlterField(
            model_name='images',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='FGPH.recipe'),
        ),
    ]
