# Generated by Django 5.0.6 on 2024-09-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0051_alter_recipe_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
