# Generated by Django 5.0.6 on 2024-09-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0052_rename_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(null=True),
        ),
    ]
