# Generated by Django 5.0.6 on 2024-09-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0053_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
