# Generated by Django 5.0.6 on 2024-09-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0054_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
