# Generated by Django 5.0.6 on 2024-09-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0055_recipe_date_edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='date_edited',
            new_name='date_modified',
        ),
    ]
