# Generated by Django 5.0.6 on 2024-09-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0056_rename_date_edited_recipe_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_time',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='serving_size',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
