# Generated by Django 5.0.6 on 2024-09-27 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0060_alter_recipe_preparation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='serving_size',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(1)]),
        ),
    ]
