# Generated by Django 5.0.6 on 2024-09-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0061_alter_recipe_serving_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='title',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
