# Generated by Django 5.0.6 on 2024-09-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0062_alter_registereduser_name_alter_registereduser_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
