# Generated by Django 5.0.6 on 2024-09-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0064_alter_registereduser_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
