# Generated by Django 5.0.6 on 2024-10-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGPH', '0065_alter_registereduser_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
