# Generated by Django 5.1 on 2024-10-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FGPH", "0066_alter_recipe_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
